# Generated by Django 5.0.6 on 2024-06-14 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_published_date_book_created_book_publish_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='created',
            new_name='published_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='book',
            name='updated',
        ),
    ]
